### ISSUE TITLE
mvn deploy issue

### ISSUE THREAD

**Issue by pawelantczak** [dzikoysk/NanoMaven#2]
Hello.

```mvn deploy``` put files under ./repositories, 
but when asked for artifact nanomaven is looking into ./repositories/releases

Am I missing something or is it a bug?

**Comment by dzikoysk** [comment]
By default, NanoMaven removes repository name from urls. For example:

Artifact:
```xml
<dependency>
    <groupId>org.panda-lang</groupId>
    <artifactId>nanomaven</artifactId>
    <version>1.0.6</version>
</dependency>
```

Distribution: 
```xml
<distributionManagement>
    <repository>
        <id>panda-repository</id>
        <url>https://repo.panda-lang.org/releases</url>
    </repository>
</distributionManagement>
```

But the URL is: `https://repo.panda-lang.org/org/panda-lang/nanomaven/1.0.6/nanomaven-1.0.6.jar`. 
If you'd like to provide repository name in paths, just enable:
https://github.com/dzikoysk/NanoMaven/blob/9ab1da1445a8c1d9030b64196b47cb8fdb41cb59/src/main/resources/nanomaven.pc#L14

**Comment by pawelantczak** [comment]
Got it.
```distributionManagement``` and ```repositories``` should share exactly the same url if ```repository-path-enabled``` is ```true```.

But in case of ```false``` ```repository-path-enabled``` maybe you can scan root dir for artifacts. 
URLs will remain consistent also in this case, meaning no additional sub dir for deploy and get.

**Comment by dzikoysk** [comment]
[1.0.7](https://github.com/dzikoysk/NanoMaven/releases) should work as you want, add this to your configuration:

```yaml
# Root directories of repositories
repositories:
- ''
- 'releases'
- 'snapshots'
```

**Comment by pawelantczak** [comment]
Thanks.
