### ISSUE TITLE
Dockerize NanoMaven

### ISSUE THREAD

**Issue by maemresen** [dzikoysk/nanomaven#50]
### Introduction
First of all, I congratulate you. It has been a very successful work.

We are developing projects and libraries with Java. We need to share JAR files to use them. So we were looking for a  lightweight solution and I can say that we found what we were looking for in this project.

### Proposal
Have you ever thought of prepare a Docker Image for NanoMaven? Or do you have this in your plans? It may be useful to have a ready to use Docker Image. There are some lightweight base Docker Images which contains Java environment. They could be used as base image.

**Comment by dzikoysk** [comment]
I didn't but it's kinda interesting idea. Do you have any specific base image in mind?

**Comment by maemresen** [comment]
It is difficult to say a special image without some research. \
First of all it should be lightweight. alpine based Docker Images could be used. 

**ex.** OpenJDK may be used directly.  \
Link: https://hub.docker.com/_/openjdk 

By the way, Java 8 needed to run app am I right?

**Comment by maemresen** [comment]
@dzikoysk 

I just try it with using following setup:

# Building Docker Image
* Create a directory
* Put `nanomaven` JAR file and the following `Dockerfile` into the directory.
```Dockerfile
FROM openjdk:8-jre-slim
ADD nanomaven.jar /usr/src/myapp/nanomaven.jar
WORKDIR /usr/src/myapp
CMD ["java", "-jar","nanomaven.jar"]
```
* Build docker image with the following command
```bash
docker build --no-cache -t nanomaven:1.0 .
```
# Deploying a Container
```bash
docker run -it -d -p <port>:80 --name <container_name> nanomaven:1.0 
``` 
* **NOTE1** `<port>`: Any other port could be used that the user want to use nanomaven with.
* **NOTE2** the `-it` parameter is important. The application has CLI which uses `STDIN` to get inputs from user. \
  **Reference**: https://stackoverflow.com/a/19689048/5732208

# Accessing NanoMaven inside Container
* To access CLI;
```bash
docker attach <container_name>
```
* **(IMPORTANT)**  To exit from CLI use the folloing key combination \
   `^P^Q`

**Comment by dzikoysk** [comment]
NanoMaven image is available in Docker Hub: https://hub.docker.com/repository/docker/dzikoysk/nanomaven 🎉 

Thanks @NorthPL for your involvement. I'll also support configuration through the parameters in #51
