### ISSUE TITLE
Command Line usage seemed not working

### ISSUE THREAD

**Issue by khmarbaise** [dzikoysk/nanomaven#56]
If I start nanomaven I get a list of commands like:
```
19:13:36.027 INFO | NanoMaven 2.2.2 Commands:
19:13:36.027 INFO |   help - List available commands
19:13:36.027 INFO |   status - Display metrics
19:13:36.027 INFO |   tokens - List all generated tokens
19:13:36.027 INFO |   keygen <path> <alias> - Generate a new access token for the given path
19:13:36.027 INFO |   purge - Clear cache
19:13:36.027 INFO |   stop - Shutdown server
19:13:36.027 INFO | 
```
But unfortunately it does not change a thing If I give them on command line like this:
```
java -jar nanomaven-2.2.2.jar help
```
If I correctly understand the code. The command line args are not given to `NanoMaven`:
```java
NanoMaven nanoMaven = new NanoMaven();
nanoMaven.launch()
```
which means from my understanding that could not work that way. Maybe I misunderstand a thing here. Maybe you can enlighten that a little bit?

**Comment by dzikoysk** [comment]
Commands are a part of the CLI - it means they can be only invoked in a working instance of application. 

```java -jar nanomaven-2.2.2.jar help```

Values provided like that are called program arguments and in fact, they're not commands.

**Comment by khmarbaise** [comment]
Hm...we can discuss about if arguments are called commands or not. For example `git commit ..` and I call `commit` a command or sub command (you can of course call it program argument)...but in the end it does not matter.

If I call NanoMaven like given:
```
java -jar nanomaven-2.2.2.jar help
```
It will simply startup the repo server like this:
```
$ ~/tools/jdk-11.0.7+10/Contents/Home/bin/java -jar nanomaven-2.2.2.jar help
19:35:46.887 INFO | 
19:35:46.892 INFO | NanoMaven 2.2.2
19:35:46.892 INFO | 
19:35:46.892 INFO | --- Preparing workspace
19:35:46.892 INFO | Using an existing configuration file
19:35:46.892 INFO | Using an existing repositories directory
19:35:46.893 INFO | Using an existing tokens data file
19:35:46.893 INFO | 
19:35:46.980 INFO | --- Loading data
19:35:47.003 INFO | Tokens: 0
19:35:47.004 INFO | 
19:35:47.005 INFO | --- Scanning to find repositories
19:35:47.005 INFO | + releases
19:35:47.005 INFO | + snapshots
19:35:47.005 INFO | 2 repositories have been found
19:35:47.005 INFO | 
19:35:47.005 INFO | Binding server at *::9100
19:35:47.033 INFO | Done (0.022s)!
19:35:47.033 INFO | 
19:35:47.033 INFO | NanoMaven 2.2.2 Commands:
19:35:47.033 INFO |   help - List available commands
19:35:47.033 INFO |   status - Display metrics
19:35:47.033 INFO |   tokens - List all generated tokens
19:35:47.033 INFO |   keygen <path> <alias> - Generate a new access token for the given path
19:35:47.033 INFO |   purge - Clear cache
19:35:47.033 INFO |   stop - Shutdown server
19:35:47.033 INFO | 
```
and it does not change anything if I give: `status` instead `help` or whatever...always the server will be started. That's based on the analysis of the code?

**Comment by khmarbaise** [comment]
After taking a deeper look into the code I found out that I have to type the commands directly into the running console. This is simply not clear from the output nor from the documentation. I would suggest to improve that.

**Comment by dzikoysk** [comment]
I see your point, I've made this division to explain the problem :) It is a good idea to support commands like `version` through the parameters.

>it means they can be only invoked in a working instance of application

I wanted to emphasize that invoking commands like `stop`, `status` or `purge` does not make sense if NanoMaven is not working and it is why I didn't support mapping program arguments into commands.

**Comment by dzikoysk** [comment]
#57

**Comment by khmarbaise** [comment]
I understand that point to divide it that way. I think it might be good way to make a special rest call to your server and support the usage of the commands via a second instance which calls the rest api... cause claming `System.in` might be an issue. In particular if you run it inside a container etc.

**Comment by dzikoysk** [comment]
I'll need a dedicated rest api in the future to hide nanomaven behind [reposilite](https://github.com/panda-lang/reposilite), but it's not a priority for these days I think 🤔

**Comment by khmarbaise** [comment]
Hey ... the priority is of course up to you. Just a thought of mine.
